-- 2022.05.15 - 프로그래머스 - #59045 보호소에서 중성화한 동물
SELECT
  I.ANIMAL_ID,
  I.ANIMAL_TYPE,
  I.NAME
FROM
  ANIMAL_INS AS I
  LEFT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE
  I.SEX_UPON_INTAKE LIKE 'Intact%'
  AND (
    O.SEX_UPON_OUTCOME LIKE 'Neutered%'
    OR O.SEX_UPON_OUTCOME LIKE 'Spayed%'
  )
ORDER BY
  I.ANIMAL_ID;