-- 2022.05.15 - 프로그래머스 - #59411 오랜 기간 보호한 동물 (2)
SELECT
  I.ANIMAL_ID,
  I.NAME
FROM
  ANIMAL_INS AS I
  LEFT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY
  O.DATETIME - I.DATETIME DESC
LIMIT
  2;